/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./src/components/app/AppCard.vue')['default']
    AppError: typeof import('./src/components/app/AppError.vue')['default']
    AppGrid: typeof import('./src/components/app/AppGrid.vue')['default']
    AppLoading: typeof import('./src/components/app/AppLoading.vue')['default']
    AppPagination: typeof import('./src/components/app/AppPagination.vue')['default']
    PostFilter: typeof import('./src/components/posts/PostFilter.vue')['default']
    PostForm: typeof import('./src/components/posts/PostForm.vue')['default']
    PostItem: typeof import('./src/components/posts/PostItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
